# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('regn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('acType', models.CharField(max_length=10)),
                ('inbound', models.IntegerField()),
                ('outbound', models.IntegerField()),
                ('ETA', models.DateTimeField()),
                ('ETD', models.DateTimeField()),
                ('bay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('action', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('dateReported', models.DateTimeField(auto_now_add=True)),
                ('dateResolved', models.DateTimeField(blank=True, null=True)),
                ('classCode', models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium'), ('buisness', 'Buisness'), ('first', 'First')], max_length=15)),
                ('category', models.CharField(choices=[('seats', 'Seats'), ('galley', 'Galley'), ('lavatory', 'Lavatory')], max_length=15)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('priority', models.IntegerField(default=0)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='api.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(choices=[(0, 'Planner'), (1, 'Supervisor'), (2, 'Technician')], null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('partID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('drawn', models.BooleanField(default=False)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='api.Defect')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='api.Spare')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='techsAssigned',
            field=models.ManyToManyField(related_name='defectsAssigned', to='api.Profile'),
        ),
    ]
