# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:12
from __future__ import unicode_literals

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    # Data migration to initialize profiles for existing users without them.
    # e.g. admin users
    User = apps.get_model("auth", "User")
    Profile = apps.get_model('api', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
