# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171024_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='defect',
            name='action',
        ),
        migrations.AddField(
            model_name='defect',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='defects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='update',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='update',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.Defect'),
        ),
    ]
