# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171025_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('dateReported', models.DateTimeField(default=django.utils.timezone.now)),
                ('classCode', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium', 'Premium'), ('buisness', 'Buisness'), ('first', 'First')], max_length=15)),
                ('category', models.CharField(blank=True, choices=[('seats', 'Seats'), ('galley', 'Galley'), ('lavatory', 'Lavatory')], max_length=15)),
                ('img', models.ImageField(blank=True, null=True, upload_to='defects')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewSpareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('drawn', models.BooleanField(default=False)),
                ('newDefect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spares', to='api.NewDefect')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawUses', to='api.Spare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='ETA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='ETD',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='acType',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='bay',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='inbound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='outbound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='dateReported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newdefect',
            name='plane',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawDefects', to='api.Aircraft'),
        ),
    ]
