# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171026_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdefect',
            name='classCode',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium', 'Premium'), ('business', 'Business'), ('first', 'First')], max_length=15),
        ),
    ]
