# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171027_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='classCode',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium'), ('business', 'Business'), ('first', 'First')], max_length=15),
        ),
    ]
